### ISSUE TITLE
Mod 0 Assessment Results

### ISSUE THREAD

**Issue by katiescruggs** [Loomus/mod_0_skills#1]
# Checklist/Rubric

#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub
* [x]  Directories are named correctly.
* [x]  Files are named correctly.
* [ ]  Files and directories are structured correctly.
> Your classes directory and files are in the proper place, but I also see a README.md file and something called mod_0_skills that should not be there.
* [x]  Initial commit was made.
* [x]  Initial commit was pushed to GitHub.

#### Part II: Top Down Design
* [x]  Larger processes were broken into smaller layers.
* [x]  Changes were added and committed with a properly formatted commit message starting with a verb and a capital letter.
* [x]  Changes were pushed to Github.

#### Part III: Classes in a System
* [x]  Directories and files were named and structured correctly.
* [x]  The attributes chosen for **Class #1** represent states or characteristics.
* [x]  The attributes chosen for **Class #2** represent states or characteristics.
* [ ]  The attributes chosen for **Class #3** represent states or characteristics.
* [ ]  The methods chosen for **Class #1** represent behaviors or actions.
* [ ]  The methods chosen for **Class #2** represent behaviors or actions.
* [ ]  The methods chosen for **Class #3** represent behaviors or actions.
* [x]  Data type (string, integer, boolean, array, hash/object, datetime) were identified for each attribute in all three classes.
* [x]  Individual changes were added and committed separately with a properly formatted commit message.
* [x]  Changes were pushed to Github.

**Mod 0 Technical Assessment Results**

* [ ]   Technical Ready
* [x]   Pending
* [ ]   Not Ready

**Comment by katiescruggs** [comment]
Good job on the assessment, Andrew! I just want you to make a few changes to this and then you will be deemed `Technical Ready`. For your classes, I was confused on what the names of your classes were and which items were attributes and methods. Would you please add a few headings to make that clear? Class names should be a singular description like "Restaurant". Also, the attributes of Class 3 Italian, Mexican, etc. should probably be booleans if you're indicating whether that restaurant serves that type of cuisine. For all of your class methods, please remove the data type. A method may return a certain data type, but all methods will be functions. You can also remove "README.md" and "mod_0_skills" from this repo. Once you have made those changes, please DM Rachel, Tim, and me. Thanks!
